### ISSUE TITLE
Permission denied during install

### ISSUE THREAD

**Issue by McLawrence** [Stvad/FuzzyDate#1]
Running  `npm install -g alfred-fuzzy-date` (as super user) results in a Permission error for the Alfred preferences:

    Error: Command failed with exit code 1 (EPERM): alfred-link
        at makeError (/usr/local/lib/node_modules/alfred-fuzzy-date/node_modules/execa/lib/error.js:59:11)
        at handlePromise (/usr/local/lib/node_modules/alfred-fuzzy-date/node_modules/execa/index.js:112:26)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async /usr/local/lib/node_modules/alfred-fuzzy-date/node_modules/alfy/init.js:7:3 {
      command: 'alfred-link',
      exitCode: 1,
      exitCodeName: 'EPERM',
      stdout: '',
      stderr: 'Error: Permission denied to read Alfred preferences at location /Users/<username>/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/alfred-fuzzy-date/node_modules/resolve-alfred-prefs/index.js:44:9)',
      all: 'Error: Permission denied to read Alfred preferences at location /Users/<username>/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n' +
    '    at module.exports (/usr/local/lib/node_modules/alfred-fuzzy-date/node_modules/resolve-alfred-prefs/index.js:44:9)',
      failed: true,
      timedOut: false,
      isCanceled: false,
      killed: false,
      signal: undefined
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! alfred-fuzzy-date@0.2.1 postinstall: `alfy-init`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the alfred-fuzzy-date@0.2.1 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I am running MacOS 10.15.3
Any idea what the problem might be?

**Comment by KickingTheTV** [comment]
I get the same error

**Comment by Stvad** [comment]
Hey there! I'm not 100% sure it's the root cause but can you try doing the following (for Terminal or iTerm, whichever one you're using):

http://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/

i.e. granting filesystem access to terminal apps.

**Comment by McLawrence** [comment]
Thanks for the help! This was the first thing I tried, but it did not change anything.

**Comment by Stvad** [comment]
I see. 

https://github.com/sindresorhus/alfred-emoj/issues/8 seems like a relevant discussion. Can you try running it without `sudo` ?

If that does not work - take a look at https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by McLawrence** [comment]
Without sudo I get the EACCES errors described in your second link. The steps described there do not work without sudo, resulting in the same EACCES errors. I can run them with sudo, however this does solve the problem. But it is clear now that this problem has nothing to do with your package.  Thanks for your help!

**Comment by McLawrence** [comment]
Update: While install the `n` version manager did not work (as it is an npm package itself and requires sudo to install) using `nvm` worked. The root cause of the problem seems to be that if node is first installed using sudo, you will need sudo rights to install all following global packages.

**Comment by KickingTheTV** [comment]
thanks I was able to resolve my issue as well!

**Comment by Stvad** [comment]
I am glad that worked :)
