### ISSUE TITLE
Error displayed in Alfred window

### ISSUE THREAD

**Issue by bierlingm** [Stvad/FuzzyDate#2]
In attempting to use the extension like `fd in two weeks` or with any other query, it returns an error:

<img width="1082" alt="Screen Shot 2022-04-28 at 6 43 09 PM" src="https://user-images.githubusercontent.com/9335771/165802708-9ff59acd-6988-4786-b84d-6c6f2720fcc4.png">

**Comment by Stvad** [comment]
Hmm, not sure what this one is about, but my first guess is a breaking change in a new version of node. Can you try using an older version (e.g. 16)?

**Comment by Stvad** [comment]
ah, actually it seems it's coming from dateformat breaking change: https://github.com/felixge/node-dateformat/releases/tag/v5.0.1 and dependency version being under specified. 
a workaround would be to force install dateformat 4. will look into updating the dependency list!

**Comment by Stvad** [comment]
ok, please try installing the latest version!

**Comment by bierlingm** [comment]
Works like a charm, thank you so much!!!!!!!!
